# Generated by Django 3.2.3 on 2021-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cases', models.IntegerField()),
                ('male_cases_estimated', models.IntegerField(null=True)),
                ('female_cases_estimated', models.IntegerField(null=True)),
                ('recovered', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField(choices=[(1, 'Last 24 Hours'), (2, 'Total'), (3, 'By District')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Last 24 hours',
            },
        ),
        migrations.CreateModel(
            name='DistrictWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
                ('total_cases', models.IntegerField()),
                ('total_male', models.IntegerField()),
                ('total_female', models.IntegerField()),
                ('daily_cases_estimated', models.IntegerField(null=True)),
                ('daily_male_estimated', models.IntegerField(null=True)),
                ('daily_female_estimated', models.IntegerField(null=True)),
                ('date_updated', models.DateField(auto_now_add=True, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Last 24 Hours'), (2, 'Total'), (3, 'By District')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.IntegerField()),
                ('total_infected', models.IntegerField()),
                ('total_male_estimated', models.IntegerField(null=True)),
                ('total_female_estimated', models.IntegerField(null=True)),
                ('recovered', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField(choices=[(1, 'Last 24 Hours'), (2, 'Total'), (3, 'By District')], default=2)),
            ],
        ),
    ]
