# Generated by Django 3.2.3 on 2021-05-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=24, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Last 24 Hours'), (2, 'Total'), (3, 'By Province')])),
                ('total_count', models.IntegerField()),
                ('male_count', models.IntegerField(blank=True, null=True)),
                ('female_count', models.IntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Last24Hours',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data.data',),
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data.data',),
        ),
    ]
