# Generated by Django 3.2.3 on 2021-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210519_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
