# Generated by Django 3.2.3 on 2021-05-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210518_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Last24Hours',
        ),
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.CreateModel(
            name='Last24Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Last 24 Hours'), (2, 'Total'), (3, 'By Province')], default=1)),
                ('total_count', models.IntegerField()),
                ('recovered_count', models.IntegerField(blank=True, null=True)),
                ('death_count', models.IntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Last 24 hours',
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Last 24 Hours'), (2, 'Total'), (3, 'By Province')], default=2)),
                ('total_count', models.IntegerField()),
                ('recovered_count', models.IntegerField(blank=True, null=True)),
                ('death_count', models.IntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
