# Generated by Django 3.2.3 on 2021-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210518_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='total_infected',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='last24hours',
            name='death_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='last24hours',
            name='recovered_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='total',
            name='death_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='total',
            name='recovered_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
