# Generated by Django 3.2.3 on 2021-05-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210518_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='last24hours',
            old_name='death_count',
            new_name='deaths',
        ),
        migrations.RenameField(
            model_name='last24hours',
            old_name='recovered_count',
            new_name='new_cases',
        ),
        migrations.RenameField(
            model_name='last24hours',
            old_name='total_count',
            new_name='recovered',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='death_count',
            new_name='deaths',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='recovered_count',
            new_name='recovered',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='total_count',
            new_name='total_cases',
        ),
    ]
