# Generated by Django 3.2.3 on 2021-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210518_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
                ('total_cases', models.IntegerField()),
                ('total_male', models.IntegerField()),
                ('total_female', models.IntegerField()),
                ('daily_cases_estimated', models.IntegerField(blank=True, null=True)),
                ('daily_male_estimated', models.IntegerField(blank=True, null=True)),
                ('daily_female_estimated', models.IntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField(choices=[(1, 'Last 24 Hours'), (2, 'Total'), (3, 'By District')], default=3)),
            ],
        ),
        migrations.AlterField(
            model_name='last24hours',
            name='category',
            field=models.IntegerField(choices=[(1, 'Last 24 Hours'), (2, 'Total'), (3, 'By District')], default=1),
        ),
        migrations.AlterField(
            model_name='total',
            name='category',
            field=models.IntegerField(choices=[(1, 'Last 24 Hours'), (2, 'Total'), (3, 'By District')], default=2),
        ),
    ]
