# Generated by Django 3.2.3 on 2021-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_area_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='area',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
