# Generated by Django 3.2.3 on 2021-05-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210519_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='date_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
