# Generated by Django 3.2.3 on 2021-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210518_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtwise',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='districtwise',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
