# Generated by Django 3.2.3 on 2021-05-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210518_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtwise',
            old_name='date',
            new_name='date_updated',
        ),
    ]
