# Generated by Django 3.2.3 on 2021-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_date_districtwise_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='last24hours',
            name='female_cases_estimated',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='last24hours',
            name='male_cases_estimated',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='total_female_estimated',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='total_male_estimated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='districtwise',
            name='daily_cases_estimated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='districtwise',
            name='daily_female_estimated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='districtwise',
            name='daily_male_estimated',
            field=models.IntegerField(null=True),
        ),
    ]
