# Generated by Django 3.2.3 on 2021-05-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20210520_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='date_updated',
        ),
    ]
