# Generated by Django 3.2.3 on 2021-05-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20210522_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='source',
            field=models.CharField(default='https://covid19.mohp.gov.np/', max_length=28),
        ),
        migrations.AlterField(
            model_name='daily',
            name='source',
            field=models.CharField(default='https://covid19.mohp.gov.np/', max_length=28),
        ),
        migrations.AlterField(
            model_name='total',
            name='source',
            field=models.CharField(default='https://covid19.mohp.gov.np/', max_length=28),
        ),
    ]
