# Generated by Django 3.2.3 on 2021-05-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
